SELECT PRODUCTS.NAME, PROVIDERS.NAME FROM PRODUCTS
INNER JOIN PROVIDERS ON PROVIDERS.ID = PRODUCTS.ID_PROVIDERS
INNER JOIN CATEGORIES ON CATEGORIES.ID = PRODUCTS.ID_CATEGORIES
AND CATEGORIES.ID = '6';